### ISSUE TITLE
bufferhint#Popup will corrupt the vim when only one buffer is opened

### ISSUE THREAD

**Issue by jesse23** [bsdelf/bufferhint#2]
Step:
1. Open one file in vim,
2. Call bufferhint#Popup.

Result: the only buffer will gone and when to some status "a   ## @".

**Comment by jesse23** [comment]
I use temp fix below:

fu! bufferhint#Popup()
    if ( 1 == len(filter(range(1, bufnr('$')), 'buflisted(v:val)')) )
        return
    endif
  .....

**Comment by bsdelf** [comment]
Sorry, I can't reproduce this bug. Which version of Vim do you use?

**Comment by jesse23** [comment]
It is because the default buffer name "[buffer]" - it conflicts with several plugins under windows platform including CtrlP. After I switch it to "~buffer~", it works correctly. Can you expose it as a preference? This is what I did:
https://github.com/jesse23/bufferhint/commit/60d3166d013812a163fb0a05d7c84d2316f2e945

By the way, this is the best buffer plugin I've met. Keep going!

**Comment by bsdelf** [comment]
A patch has been applied! Thanks for your suggestion : )
d129d0c6878428936bb5c2382b6306ffcf4998bf
