### ISSUE TITLE
Index gets confused by Quickfix

### ISSUE THREAD

**Issue by FiloSottile** [bsdelf/bufferhint#3]
If I run Popup with a Quickfix panel open, all sorts of weird behaviors happen, from "buffer number 9 not found in index" to simply opening the wrong buffer when I select one.

At one point it opened a copy of the Quickfix buffer itself.

I suspect you should just ignore Quickfix buffers.

Probably the same for Location boxes.

(Thanks for the plugin!)

**Comment by bsdelf** [comment]
Sorry for stalls.

Now the bug should be fixed with this commit: https://github.com/bsdelf/bufferhint/commit/6aabcde82f5238ce0578763e74890c19a481046a
